-- 05/27 : View
grant create view to scott;


-- [View 용도]
-- DIFFERENT APPEARANCES FOR THE SAME DATA


-- DIFF_RETURN_TBL TABLE 생성
CREATE TABLE DIFF_RETURN_TBL
AS SELECT OWNER, TABLE_NAME FROM DBA_TABLES;


-- DATA 갯수 확인
SELECT * FROM DIFF_RETURN_TBL;
SELECT COUNT(*) FROM DIFF_RETURN_TBL; -- 2135개


-- DIFF_RETURN_VIEW 생성
CREATE OR REPLACE VIEW DIFF_RETURN_VIEW
AS SELECT * FROM DIFF_RETURN_TBL WHERE OWNER = USER;

-- DIFF_RETURN_TBL 조회
SELECT * FROM DIFF_RETURN_TBL;
SELECT COUNT(*) FROM DIFF_RETURN_TBL; -- 2135개

-- DIFF_RETURN_VIEW 조회
SELECT * FROM DIFF_RETURN_VIEW;
SELECT COUNT(*) FROM DIFF_RETURN_VIEW; -- 128개

/*
SCOTT 계정에서 뷰 조회해보기 => 조회 불가!!

ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:
181행, 15열에서 오류 발생

SELECT * FROM DIFF_RETURN_VIEW; 
*/


-- DIFF_RETURN_VIEW 권한을 PUBLIC_USER로 변경
GRANT SELECT ON DIFF_RETURN_VIEW TO PUBLIC;