-- SESSION (A)

-- 1번 실행
UPDATE EMP SET SAL=0 WHERE DEPTNO=10;

-- 3번 실행
SELECT DEPTNO, ENAME, SAL FROM EMP WHERE DEPTNO = 10;

-- 4번 실행
COMMIT;

-- 6번 실행 ( SESSION (A) - 1번 재실행 )
SELECT DEPTNO, ENAME, SAL FROM EMP WHERE DEPTNO = 10;


