SET SERVEROUTPUT ON

DECLARE
    V_EMPNO NUMBER(4) := 0;
    V_ENAME VARCHAR2(10);
    V_DEPTNO NUMBER(2);
BEGIN
    V_EMPNO := 7779;
    V_ENAME := 'PL/SQL';
    INSERT INTO EMP(EMPNO, DEPTNO, ENAME) VALUES(V_EMPNO, V_DEPTNO, V_ENAME);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('INSERT ERR : ' || SQLERRM);
        ROLLBACK;
END;
/