-- 1. 오류나는 PL/SQL
CREATE OR REPLACE FUNCTION CALC_BONUS(P_SALARY IN NUMBER, P_DEPTNO IN NUMBER)
RETURN NUMBER
IS
    V_BONUS_RATE NUMBER :=0;
    V_BONUS NUMBER(7,2) :=0;
BEGIN
    -- 근무 부서별로 Bonus 차등 지급
    IF P_DEPTNO = 10 THEN
        V_BONUS_RATE := 0.1;
    ELSIF P_DEPTNO = 20 THEN
        V_BONUS_RATE := 0.2;
    ELSIF P_DEPTNO = 30 THEN
        V_BONUS_RATE := 0.3;
    ELSE
        V_BONUS_RATE := 0.05;
    END IF;
    V_BONUS := ROUND(NVL(P_SALARY, 0) * C_BONUS_RATE, 2);
    -- 오류(16,41): PLS-00201: 'C_BONUS_RATE' 식별자가 정의되어야 합니다
    RETURN V_BONUS;
END CALC_BONUS;
/

-- 2. 오류 수정한 PL/SQL
CREATE OR REPLACE FUNCTION CALC_BONUS(P_SALARY IN NUMBER, P_DEPTNO IN NUMBER)
RETURN NUMBER
IS
    V_BONUS_RATE NUMBER :=0;
    V_BONUS NUMBER(7,2) :=0;
BEGIN
    -- 근무 부서별로 Bonus 차등 지급
    IF P_DEPTNO = 10 THEN
        V_BONUS_RATE := 0.1;
    ELSIF P_DEPTNO = 20 THEN
        V_BONUS_RATE := 0.2;
    ELSIF P_DEPTNO = 30 THEN
        V_BONUS_RATE := 0.3;
    ELSE
        V_BONUS_RATE := 0.05;
    END IF;
    -- V_BONUS := ROUND(NVL(P_SALARY, 0) * C_BONUS_RATE, 2);
    -- 오류(16,41): PLS-00201: 'C_BONUS_RATE' 식별자가 정의되어야 합니다
    V_BONUS := ROUND(NVL(P_SALARY, 0) * V_BONUS_RATE, 2);
    RETURN V_BONUS;
END CALC_BONUS;
/