SELECT * FROM LEASE_EXPIRE;

-- 지역별 총 만기도래 총합 구하기 
SELECT GU, SUM(COUNT) FROM LEASE_EXPIRE GROUP BY GU ORDER BY SUM(COUNT) DESC;

-- 가장 많은 지역 구하기 : 송파구
SELECT * FROM (
    SELECT GU, SUM(COUNT) FROM LEASE_EXPIRE GROUP BY GU ORDER BY SUM(COUNT) DESC
) WHERE ROWNUM = 1;

SELECT * FROM CUSTOMER;
SELECT * FROM LEASE_EXPIRE;
SELECT L.GU FROM LEASE_EXPIRE L, CUSTOMER C
WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
GROUP BY L.GU
ORDER BY L.GU;


SELECT L.GU , COUNT(C.ID) FROM 
(SELECT GU, SUM(COUNT) 
FROM LEASE_EXPIRE GROUP BY GU) L, CUSTOMER C
WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
GROUP BY L.GU
ORDER BY L.GU;


SELECT L.GU , COUNT(C.ID) 
FROM 
    (SELECT GU, COUNT
FROM
(SELECT GU, SUM(COUNT) AS COUNT FROM LEASE_EXPIRE GROUP BY GU ORDER BY COUNT DESC)
WHERE ROWNUM <= 3) L, CUSTOMER C
WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
GROUP BY L.GU
ORDER BY L.GU;
-- 메일, 전화번호, 이름, ID


SELECT ID, PWD, NAME, MOBILE_NO, EMAIL , CREDIT_LIMIT, TRIM(SUBSTR(ADDRESS1,4,4))
FROM CUSTOMER
WHERE CREDIT_LIMIT >=
    (SELECT CREDIT_LIMIT
    FROM (SELECT CREDIT_LIMIT
          FROM (SELECT CREDIT_LIMIT
                FROM CUSTOMER
                ORDER BY CREDIT_LIMIT DESC)
          WHERE ROWNUM <= (SELECT COUNT(ID) FROM CUSTOMER) * 0.1
          ORDER BY CREDIT_LIMIT)
    WHERE ROWNUM = 1) AND ADDRESS1 LIKE '%서울%'; -- 신용도 상위 10퍼센트 고객의 신용도 최하 점수


-- 주제 : [ 전세대출만기일 도래 건수가 많은 서울 지역의 고객 중, 신용 등급이 상위 10%인 고객 목록 출력하기 ]
-- JOIN 진짜 최종!!!!
SELECT C.ID, C.PWD, C.NAME, C.MOBILE_NO, C.EMAIL , C.CREDIT_LIMIT, C.GU FROM 
(
    -- 서울에 사는 고객 중, 신용 등급이 상위 10%인 고객 TABLE
    SELECT ID, PWD, NAME, MOBILE_NO, EMAIL , CREDIT_LIMIT, TRIM(SUBSTR(ADDRESS1,4,4)) AS GU
    FROM CUSTOMER
    WHERE CREDIT_LIMIT >=
        (SELECT CREDIT_LIMIT
        FROM (SELECT CREDIT_LIMIT
              FROM (SELECT CREDIT_LIMIT
                    FROM CUSTOMER
                    ORDER BY CREDIT_LIMIT DESC)
              WHERE ROWNUM <= (SELECT COUNT(ID) FROM CUSTOMER) * 0.1
              ORDER BY CREDIT_LIMIT)
        WHERE ROWNUM = 1) AND ADDRESS1 LIKE '%서울%'
) C , (
    -- 서울 내 전세대출 만기일이 도래한 건수가 가장 많은 지역 테이블
    SELECT L.GU
    FROM 
        (SELECT GU, COUNT
    FROM
    (SELECT GU, SUM(COUNT) AS COUNT FROM LEASE_EXPIRE GROUP BY GU ORDER BY COUNT DESC)
    WHERE ROWNUM = 1) L, CUSTOMER C
    WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
    GROUP BY L.GU
    ORDER BY L.GU
) L
WHERE C.GU = L.GU
ORDER BY GU;




-- JOIN 최종!!!!
SELECT C.ID, C.PWD, C.NAME, C.MOBILE_NO, C.EMAIL , C.CREDIT_LIMIT, C.GU FROM 
(
    SELECT ID, PWD, NAME, MOBILE_NO, EMAIL , CREDIT_LIMIT, TRIM(SUBSTR(ADDRESS1,4,4)) AS GU
    FROM CUSTOMER
    WHERE CREDIT_LIMIT >=
        (SELECT CREDIT_LIMIT
        FROM (SELECT CREDIT_LIMIT
              FROM (SELECT CREDIT_LIMIT
                    FROM CUSTOMER
                    ORDER BY CREDIT_LIMIT DESC)
              WHERE ROWNUM <= (SELECT COUNT(ID) FROM CUSTOMER) * 0.1
              ORDER BY CREDIT_LIMIT)
        WHERE ROWNUM = 1) AND ADDRESS1 LIKE '%서울%'
) C , (
    SELECT L.GU
    FROM 
        (SELECT GU, COUNT
    FROM
    (SELECT GU, SUM(COUNT) AS COUNT FROM LEASE_EXPIRE GROUP BY GU ORDER BY COUNT DESC)
    WHERE ROWNUM <= 3) L, CUSTOMER C
    WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
    GROUP BY L.GU
    ORDER BY L.GU
) L
WHERE C.GU = L.GU
ORDER BY GU;




SELECT L.GU
FROM 
    (SELECT GU, COUNT
FROM
(SELECT GU, SUM(COUNT) AS COUNT FROM LEASE_EXPIRE GROUP BY GU ORDER BY COUNT DESC)
WHERE ROWNUM <= 3) L, CUSTOMER C
WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
GROUP BY L.GU
ORDER BY L.GU;


SELECT ID, PWD, NAME, MOBILE_NO, EMAIL , CREDIT_LIMIT, TRIM(SUBSTR(ADDRESS1,4,4)) AS GU
FROM CUSTOMER
WHERE CREDIT_LIMIT >=
    (SELECT CREDIT_LIMIT
    FROM (SELECT CREDIT_LIMIT
          FROM (SELECT CREDIT_LIMIT
                FROM CUSTOMER
                ORDER BY CREDIT_LIMIT DESC)
          WHERE ROWNUM <= (SELECT COUNT(ID) FROM CUSTOMER) * 0.1
          ORDER BY CREDIT_LIMIT)
    WHERE ROWNUM = 1) AND ADDRESS1 LIKE '%서울%'; -- 신용도 상위 10퍼센트 고객의 신용도 최하 점수



SELECT GU, COUNT
FROM
(SELECT GU, SUM(COUNT) AS COUNT FROM LEASE_EXPIRE GROUP BY GU ORDER BY COUNT DESC)
WHERE ROWNUM <= 3;


SELECT GU, SUM(COUNT) FROM LEASE_EXPIRE GROUP BY GU;




SELECT L.*,C.* FROM LEASE_EXPIRE L, CUSTOMER C
WHERE L.GU = TRIM(SUBSTR(C.ADDRESS1,4,4))
ORDER BY L.GU;




-- 주제 바꿈! 
-- 새로운 주제 : [지역별 만기 대출 도래 건수와 신용등급의 상관관계]
SEL

