-- <05/17> Constraint

-- [ NOT NULL (필수입력사항 ]
@T_CONS.SQL

SELECT * FROM TST_CUSTOMER;

/*
ⓐ Block 공간 활용 Parameter PCTFREE , PCTUSED, INITRANS, MAXTRANS에 대해 설명 하십시요
 
ⓑ TABLESPACE 정의 및 용도 와 STORAGE에 대해 설명 하십시요
*/

-- 1.
DESC TST_CUSTOMER;
/*
ID   NOT NULL VARCHAR2(8)  
PWD  NOT NULL VARCHAR2(8)  
NAME          VARCHAR2(20) 
SEX           CHAR(1)      
AGE           NUMBER(3)    
*/

-- 2. (ID, PWD, NAME, SEX, AGE), ('xman','ok','kang','M',21)인 회원 입력
INSERT INTO TST_CUSTOMER(ID, PWD, NAME, SEX, AGE) VALUES('xman','ok','kang','M',21);
ROLLBACK;

-- 3. (ID,PWD,NAME,SEX,AGE)('XMAN','no','kim', 'T',-20);
INSERT INTO TST_CUSTOMER(ID,PWD,NAME,SEX,AGE) VALUES('XMAN','no','kim', 'T',-20);

-- 4.



-- CHECK에 NULL값이 들어가는가? YES! 

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='TST_CUSTOMER';


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='CUSOTMER' ORDER BY CONSTRAINT_NAME, POSITION;


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='CUSOTMER' 
ORDER BY CONSTRAINT_NAME, POSITION;


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='TST_CUSTOMER' 
ORDER BY CONSTRAINT_NAME, POSITION;


select * from TST_CUSTOMER2;


SELECT * FROM TST_CUSTOMER2;


SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT * FROM USER_TRIGGERS;

SELECT * FROM TST_CUSTOMER3;


SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'CUSTOMER3';

SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'TST_CUSTOMER3';


SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'TST_CUSTOMER3' ORDER BY INDEX_NAME, COLUMN_POSITION;


SELECT * FROM TST_CUSTOMER4;


SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'TST_CUSTOMER4';


SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'TST_CUSTOMER4' ORDER BY INDEX_NAME, COLUMN_POSITION;
