SELECT * FROM TST_CUSTOMER;


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='CUSTOMER';


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='TST_CUSTOMER';


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='CUSOTMER' ORDER BY CONSTRAINT_NAME, POSITION;


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='CUSOTMER' 
ORDER BY CONSTRAINT_NAME, POSITION;


SELECT TABLE_NAME, CONSTRAINT_NAME, POSITION, COLUMN_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME='TST_CUSTOMER' 
ORDER BY CONSTRAINT_NAME, POSITION;


select * from TST_CUSTOMER2;


SELECT * FROM TST_CUSTOMER2;


SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT * FROM USER_TRIGGERS;

SELECT * FROM TST_CUSTOMER3;


SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'CUSTOMER3';

SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'TST_CUSTOMER3';


SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'TST_CUSTOMER3' ORDER BY INDEX_NAME, COLUMN_POSITION;


SELECT * FROM TST_CUSTOMER4;


SELECT INDEX_NAME, INDEX_TYPE, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'TST_CUSTOMER4';


SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'TST_CUSTOMER4' ORDER BY INDEX_NAME, COLUMN_POSITION;
