CREATE TABLE TST_DEPARTMENT(
    DEPTNO VARCHAR2(2) CONSTRAINT TST_DEPARTMENT_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(10) CONSTRAINT TST_DEPARTMENT_DNAME_NN NOT NULL
);

CREATE TABLE TST_EMPLOYEE(
    사번 VARCHAR2(8) PRIMARY KEY, 
    이름 VARCHAR2(10), 
    DEPTNO VARCHAR2(2) NOT NULL,
    CONSTRAINT TST_EMPLOYEE_DEPARTMENT_DEPTNO_FK FOREIGN KEY(DEPTNO) -- TABLE LEVEL 제약사항
    REFERENCES TST_DEPARTMENT(DEPTNO) 
);