DROP TABLE SCOTT.TST_CUSTOMER; 

CREATE TABLE SCOTT.TST_CUSTOMER(
    ID VARCHAR2(8) NOT NULL,
    PWD VARCHAR2(8) CONSTRAINT TST_CUSTOMER_PWD_NN NOT NULL,
    NAME VARCHAR2(20), -- 이름
    SEX CHAR(1), -- 성별
    AGE NUMBER(3) -- 나이
)TABLESPACE USERS
-- PCTFREE, PCTUSED : 블럭 단위의 공간활용 파라미터
-- PCTFREE : 프리로 남겨둘 %(퍼센테이지)
-- INITRANS : 이니셜 트랜젝션
-- MAXTRANS : 맥시멈 트랜젝션
PCTFREE 5 PCTUSED 60 INITRANS 2 MAXTRANS 20
-- STORAGE : 양을 할당하라, 처음에는 100K, 그 다음에 더 필요하면 100K를 할당해라, 
STORAGE(INITIAL 100K NEXT 100K MINEXTENTS 3 MAXEXTENTS 10 PCTINCREASE 0);