DROP TABLE SCOTT.TST_CUSTOMER2;

CREATE TABLE TST_CUSTOMER2(
    ID VARCHAR2(8) NOT NULL,
    PWD VARCHAR2(8) CONSTRAINT TST_CUSTOMER2_PWD_NN NOT NULL,
    NAME VARCHAR2(20), 
    SEX CHAR(1) CONSTRAINT TST_CUSTOMER2_SEX_CK CHECK(SEX IN ('M', 'F')), 
    AGE NUMBER(3) CHECK (AGE > 0 AND AGE < 100)
);