CREATE TABLE TST_CUSTOMER4(
    ID VARCHAR2(8) CONSTRAINT TST_CUSTOMER4_ID_PK PRIMARY KEY,
    PWD VARCHAR2(8) NOT NULL,
    NAME VARCHAR2(20), 
    SEX CHAR(1) DEFAULT 'M' CONSTRAINT TST_CUSTOMER4_SEX_CK CHECK(SEX IN ('M', 'F')), 
    MOBILE VARCHAR2(14) CONSTRAINT TST_CUSTOMER_MOBILE_UK UNIQUE, -- 핸드폰 번호
    AGE NUMBER(3) DEFAULT 18
);