REM CURSOR_ATT_IMP.SQL
SET SERVEROUTPUT ON

SELECT * FROM EMP;

BEGIN
    -- 첫번째 암시적 커서 
    DELETE FROM EMP WHERE SAL > 2000;
    DBMS_OUTPUT.PUT_LINE('[1-DELETE]'||TO_CHAR(SQL%ROWCOUNT||'ROWS IS DELETED'));
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('SQL%FOUND = TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SQL%NOTFOUND = FALSE');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('----------------------------------');
    
    -- 두번째 암시적 커서
    DELETE FROM EMP WHERE SAL > 2000;
    DBMS_OUTPUT.PUT_LINE('[1-DELETE]'||TO_CHAR(SQL%ROWCOUNT||'ROWS IS DELETED'));
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('SQL%FOUND = TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SQL%NOTFOUND = FALSE');
    END IF;
END;
/

SELECT * FROM EMP;

ROLLBACK;
SELECT * FROM EMP;
