CREATE OR REPLACE PACKAGE BODY P_EMPLOYEE
AS
    V_ENAME EMP.ENAME%TYPE;
    V_ROWS NUMBER(6);
    
    FUNCTION PRVT_FUNC(P_NUM IN NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN P_NUM;
    END PRVT_FUNC;
    
    PROCEDURE INSERT_EMP(P_EMPNO NUMBER, P_ENAME VARCHAR2, P_JOB VARCHAR2, P_SAL NUMBER, P_DEPTNO NUMBER)
    IS 
    BEGIN
        INSERT INTO EMP(EMPNO, ENAME, JOB, SAL, DEPTNO) VALUES(P_EMPNO, P_ENAME, P_JOB, P_SAL, P_DEPTNO);
        COMMIT;
    END INSERT_EMP;
    
    PROCEDURE DELETE_EMP(P_EMPNO EMP.EMPNO%TYPE) IS 
    BEGIN
        DELETE FROM EMP WHERE EMPNO = P_EMPNO;
        COMMIT;
        GV_ROWS := GV_ROWS + SQL%ROWCOUNT;
        V_ROWS := PRVT_FUNC(GV_ROWS);
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            WRITE_LOG('P_EMPLOYEE.DELETE', SQLERRM, 'VALUES : [EMPNO] => '|| P_EMPNO);
    END DELETE_EMP;
    
    FUNCTION SEARCH_MNG(P_EMPNO EMP.EMPNO%TYPE) RETURN VARCHAR2
    IS
        V_ENAME EMP.ENAME%TYPE;
    BEGIN
        SELECT ENAME INTO V_NAME FROM EMP
        WHERE 
    
    