-- 명세를 모아둔 것
DESC DBMS_OUTPUT;

CREATE OR REPLACE PACKAGE P_GLOBAL_VARS
AS
    -- 명세에서 선언하는 경우 PUBLIC하게 사용
    LAST_CHANGE_DATE DATE;
    MAX_VALUE NUMBER(4);
END;
/

DESC P_GLOBAL_VARS -- HEADER 영역에서 정의한 변수는 DESC를 통해서 볼 수 없다.

SET SERVEROUTPUT ON

-- 첫번째 BLOCK에서 변수값 초기화
BEGIN
    P_GLOBAL_VARS.MAX_VALUE := 3000;
    P_GLOBAL_VARS.LAST_CHANGE_DATE := SYSDATE;
    DBMS_OUTPUT.PUT_LINE('BLOCK1 P_GLOBAL_VARS.MAX_VALUE = '||P_GLOBAL_VARS.MAX_VALUE);
END;
/

-- 서로 다른 독립적인 BLOCK간에 DATA 공유
BEGIN
    P_GLOBAL_VARS.MAX_VALUE := P_GLOBAL_VARS.MAX_VALUE + 3000;
    DBMS_OUTPUT.PUT_LINE('BLOCK2 P_GLOBAL_VARS.MAX_VALUE = '|| P_GLOBAL_VARS.MAX_VALUE);
    DBMS_OUTPUT.PUT_LINE('BLOCK2 P_GLOBAL_VARS.LAST_CHANGE_DATE = '|| TO_CHAR(P_GLOBAL_VARS.LAST_CHANGE_DATE, 'YYYY-MM-DD'));
END;
/

/*
Package P_GLOBAL_VARS이(가) 컴파일되었습니다.


BLOCK1 P_GLOBAL_VARS.MAX_VALUE = 3000


PL/SQL 프로시저가 성공적으로 완료되었습니다.

BLOCK2 P_GLOBAL_VARS.MAX_VALUE = 6000
BLOCK2 P_GLOBAL_VARS.LAST_CHANGE_DATE = 2021-07-05


PL/SQL 프로시저가 성공적으로 완료되었습니다.
*/