
-- 테이블 생성
CREATE TABLE MERGE_CHART (
	ID	NUMBER,
	AMOUNT	NUMBER
);

INSERT INTO MERGE_CHART VALUES (1, 3000);
INSERT INTO MERGE_CHART VALUES (2, 4000);
INSERT INTO MERGE_CHART VALUES (3, 6000);
INSERT INTO MERGE_CHART VALUES (4, 1000);
INSERT INTO MERGE_CHART VALUES (5, 1000);

CREATE TABLE MERGE_CHART_NEW (
	ID	NUMBER,
	AMOUNT	NUMBER
);

INSERT INTO MERGE_CHART_NEW VALUES (1, 4000); -- MATCH 증가 / UPDATE
INSERT INTO MERGE_CHART_NEW VALUES (2, 5000); -- MATCH 증가 / UPDATE
INSERT INTO MERGE_CHART_NEW VALUES (3, null); -- MATCH null / DELETE
INSERT INTO MERGE_CHART_NEW VALUES (4, 1000); -- MATCH 유지 / NOT UPDATE
INSERT INTO MERGE_CHART_NEW VALUES (5, 1000); -- MATCH 유지 / NOT UPDATE
INSERT INTO MERGE_CHART_NEW VALUES (6, 7000); -- NOT MATCH / INSERT
INSERT INTO MERGE_CHART_NEW VALUES (7, 8000); -- NOT MATCH / INSERT
COMMIT;

-- 만들어진 테이블 조회
SELECT * FROM MERGE_CHART;
SELECT * FROM MERGE_CHART_NEW;

-- 병합 실행
MERGE INTO MERGE_CHART M1
USING MERGE_CHART_NEW M2
ON ( M1.ID = M2.ID )
WHEN MATCHED THEN
	UPDATE SET M1.AMOUNT = M2.AMOUNT
    DELETE WHERE (M1.AMOUNT IS NULL)
WHEN NOT MATCHED THEN
	INSERT VALUES(M2.ID, M2.AMOUNT);

-- 병합된 테이블 확인
SELECT * FROM MERGE_CHART;
SELECT * FROM MERGE_CHART_NEW;

-- 되돌리기
ROLLBACK;

-- 되돌려진 테이블 확인
SELECT * FROM MERGE_CHART;
SELECT * FROM MERGE_CHART_NEW;


