/* 참조 연산자 */
SET SERVEROUTPUT ON

DECLARE
    REC_EMP EMP%ROWTYPE;
    V_EMPNO EMP.EMPNO%TYPE;
BEGIN
    -- 1개의 ROW를 SELECT해서 RECORD에 저장
    SELECT * INTO REC_EMP FROM EMP WHERE EMPNO = 7369;
    
    DBMS_OUTPUT.PUT_LINE('EMPNO => '|| REC_EMP.EMPNO);
    DBMS_OUTPUT.PUT_LINE('ENAME => '|| REC_EMP.ENAME);
    DBMS_OUTPUT.PUT_LINE('JOB => '|| REC_EMP.JOB);
    DBMS_OUTPUT.PUT_LINE('MGR => '|| REC_EMP.MGR);
    DBMS_OUTPUT.PUT_LINE('HIREDATE => '|| REC_EMP.HIREDATE);
    DBMS_OUTPUT.PUT_LINE('SAL => '|| REC_EMP.SAL);
    
    -- RECORD의 개개 FIELD를 독립적으로 사용한 경우
    SELECT EMPNO, ENAME INTO V_EMPNO, REC_EMP.ENAME
    FROM EMP
    WHERE EMPNO = 7369;
    
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    DBMS_OUTPUT.PUT_LINE('EMPNO => '|| V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('ENAME => '|| REC_EMP.ENAME);
END;
/

/*
EMPNO => 7369
ENAME => SMITH
JOB => CLERK
MGR => 7902
HIREDATE => 80/12/17
SAL => 800
-----------------------------
EMPNO => 7369
ENAME => SMITH
*/


-- 2. SELECT 문에 INTO가 없는 경우
DECLARE
    REC_EMP EMP%ROWTYPE;
    V_EMPNO EMP.EMPNO%TYPE;
BEGIN
    -- 1개의 ROW를 SELECT해서 RECORD에 저장
    SELECT * FROM EMP WHERE EMPNO = 7369;
    
    DBMS_OUTPUT.PUT_LINE('EMPNO => '|| REC_EMP.EMPNO);
    DBMS_OUTPUT.PUT_LINE('ENAME => '|| REC_EMP.ENAME);
    DBMS_OUTPUT.PUT_LINE('JOB => '|| REC_EMP.JOB);
    DBMS_OUTPUT.PUT_LINE('MGR => '|| REC_EMP.MGR);
    DBMS_OUTPUT.PUT_LINE('HIREDATE => '|| REC_EMP.HIREDATE);
    DBMS_OUTPUT.PUT_LINE('SAL => '|| REC_EMP.SAL);
    
    -- RECORD의 개개 FIELD를 독립적으로 사용한 경우
    SELECT EMPNO, ENAME INTO V_EMPNO, REC_EMP.ENAME
    FROM EMP
    WHERE EMPNO = 7369;
    
    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    DBMS_OUTPUT.PUT_LINE('EMPNO => '|| V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('ENAME => '|| REC_EMP.ENAME);
END;
/

/*
오류 보고 -
ORA-06550: 줄 6, 열5:PLS-00428: 해당 SELECT 문에 INTO 절이 필요합니다.
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error
*/