-- %TYPE에 SELECT되는 대상 데이터가 여러개인 것을 INTO 했을 때!

SET SERVEROUTPUT ON

DECLARE
    V_EMPNO EMP.EMPNO%TYPE;
    V_ENAME EMP.ENAME%TYPE;
    V_HIREDATE EMP.HIREDATE%TYPE;
BEGIN
    SELECT EMPNO, ENAME, HIREDATE INTO V_EMPNO, V_ENAME, V_HIREDATE
    FROM EMP
    WHERE EMPNO >= 1;
    
    DBMS_OUTPUT.PUT_LINE('SELECTED EXACTLY ONE ROW ' || V_EMPNO);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!!!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('TOO MANY ROWS FOUND');
END;
/

/*
TOO MANY ROWS FOUND
*/